#!/bin/sh

APP_NAME="scmserver"

if [ "$1" = "0" ] || [ "$1" = "remove" ]; then
    echo "Stopping and disabling $APP_NAME service..."
    if [ -d /run/systemd/system ]; then
        systemctl stop "$APP_NAME.service" >/dev/null 2>&1 || true
        systemctl disable "$APP_NAME.service" >/dev/null 2>&1 || true
    fi
fi

exit 0
