#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    echo "Removing logs for scmclient..."
    rm -rf /var/log/scmclient
fi

if [ "$1" = "remove" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload >/dev/null || true
    fi
fi

exit 0
