#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl stop scmclient.service >/dev/null || true
        systemctl disable scmclient.service >/dev/null || true
    fi
fi

exit 0
