#!/bin/sh

if [ -x /usr/sbin/sysrc ]; then
    /usr/sbin/sysrc -x scmclient_enable
fi

echo "scmclient removed. Configuration and keys in /usr/local/etc/openscm and /var/db/openscm were NOT deleted."

exit 0

