name: OpenSCM Manual Testing

on:
  workflow_dispatch:

jobs:
  test-build:
    name: Test Build ${{ matrix.app }} (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [client, server]
        target: ["aarch64-unknown-linux-musl"]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update && sudo apt-get install -y nsis
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          cargo install cargo-zigbuild
          rustup target add ${{ matrix.target }}

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Build
        run: |
          mkdir -p build/bin
          cargo zigbuild --release --target ${{ matrix.target }} -p scm${{ matrix.app }}
          cp target/${{ matrix.target }}/release/scm${{ matrix.app }} build/bin/
      
      - name: Package
        run: |
          mkdir -p dist
          APP_NAME="scm${{ matrix.app }}"
          VERSION=$(grep -m 1 '^version =' ${APP_NAME}/Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
          RELEASE=${{ github.run_number }}

          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]]; then
            DEB_FILE="${APP_NAME}_${VERSION}-${RELEASE}_arm64.deb"
            RPM_FILE=${APP_NAME}-${VERSION}-${RELEASE}.aarch64.rpm"
            PKG_FILE=${APP_NAME}_${VERSION}-${RELEASE}_aarch64.pkg.tar.zst"
            echo "Packaging .deb for ${{ matrix.target }}"
            APP_NAME=$APP_NAME ARCH="arm64" VERSION=$VERSION RELEASE=$RELEASE \
            nfpm pkg --packager deb --config "config/${APP_NAME}.yaml" --target "dist/${DEB_FILE}"
            echo "Packaging .rpm for ${{ matrix.target }}"
            APP_NAME=$APP_NAME ARCH="aarch64" VERSION=$VERSION RELEASE=$RELEASE \
            nfpm pkg --packager deb --config "config/${APP_NAME}.yaml" --target "dist/${RPM_FILE}"
            echo "Packaging .pkg.tar.zst for ${{ matrix.target }}"
            APP_NAME=${APP_NAME} ARCH="aarch64" VERSION=${VERSION} RELEASE=${RELEASE} \ 
            nfpm pkg --packager archlinux --config "config/${APP_NAME}.yaml" --target "dist/${PKG_FILE}"           
          fi

      - name: Upload Testing Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Use matrix variables for the name so it is unique for each job
          name: ${{ env.MY_ARTIFACT_NAME }}
          path: dist/*

